# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab21a87eaa63b8e9a9689758a4362ab6a3c82cc92fa49727315a1829ac96ca5cb3125dd698277d430d4b7ee534b691fdcdb061010e5f6100b593b0ed6f6c6dee

test:
  secret_key_base: a21e532dc57d4cd826982626503a75039e42afb6653be855c981efb81c54d5d492de1fcd2d437daf28dbcf4035c0f6cbb66329398bb3379c4bf840908e81cdbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
